const assert=require('node:assert/strict');
require('../progression.js');
const career=globalThis.JetlevProgression;
const data=new Map();
const storage={getItem:key=>data.get(key)??null,setItem:(key,value)=>data.set(key,value)};
let profile=career.load(storage);
assert.equal(profile.bank,0);
assert.equal(career.selectIsland(profile,'harbor'),false);
assert.equal(career.equip(profile,'aqua'),false);
assert.equal(career.recordRun(profile,{coins:100}).credited,false,'runs require a stable ID for duplicate protection');
let reward=career.recordRun(profile,{id:'one',distance:350,coins:35,perfects:2});
assert.equal(reward.earned,35);
assert.equal(profile.bank,35);
assert.equal(career.recordRun(profile,{id:'one',distance:350,coins:35,perfects:2}).credited,false);
assert.equal(profile.bank,35,'a repeated finish cannot award twice');
reward=career.recordRun(profile,{id:'two',distance:250,coins:25,perfects:1});
assert.deepEqual(reward.unlocked,['harbor']);
assert.equal(reward.completed.length,3);
assert.equal(career.selectIsland(profile,'harbor'),true);
assert.equal(career.selectIsland(profile,'sunset'),false);
assert.equal(career.recordRun(profile,{id:'locked',islandId:'sunset',coins:999}).credited,false);
assert.equal(career.buy(profile,'coral'),false,'insufficient funds never spend');
career.recordRun(profile,{id:'three',distance:1500,coins:150,perfects:6});
assert.equal(career.isUnlocked(profile,'sunset'),true);
assert.equal(career.buy(profile,'coral'),true);
assert.equal(profile.bank,110);
assert.equal(career.buy(profile,'coral'),false,'owned items cannot be charged again');
assert.equal(career.equip(profile,'coral'),true);
assert.equal(career.selectIsland(profile,'lagoon'),true,'completed islands stay replayable');
assert.equal(career.missionProgress(profile,'lagoon')[0].value,600);
assert.equal(career.save(profile,storage),true);
assert.deepEqual(career.load(storage),profile,'career round trips with equipped cosmetic and run IDs');
assert.equal(career.recordRun(career.load(storage),{id:'three',coins:150}).credited,false,'duplicate protection persists across reloads');
const bank=profile.bank;
career.recordRun(profile,{id:'invalid-stats',distance:Infinity,coins:-50,perfects:'100',shieldSaves:NaN});
assert.equal(profile.bank,bank);
assert.equal(profile.islands.lagoon.distance,600);
assert.equal(career.load({getItem(){throw Error('private storage');}}).bank,0);
assert.equal(career.save(profile,{setItem(){throw Error('quota');}}),false);
storage.setItem(career.KEY,'broken JSON');
assert.equal(career.load(storage).selectedIsland,'lagoon');
storage.setItem(career.KEY,JSON.stringify({version:1,bank:-123,selectedIsland:'sunset',equipped:'aqua',owned:['bad'],islands:{lagoon:{distance:Infinity}},runIds:[null,3,'valid']}));
profile=career.load(storage);
assert.equal(profile.bank,0);
assert.equal(profile.selectedIsland,'lagoon');
assert.equal(profile.equipped,'classic');
assert.deepEqual(profile.owned,['classic']);
assert.deepEqual(profile.runIds,['valid']);
assert.deepEqual(career.missionProgress(profile,'unknown'),[]);
console.log('Progression tests passed: cumulative islands, replay, one-time rewards, cosmetic economy, persistence and corrupt storage.');
